---
apiVersion: v1
kind: Pod
metadata: 
  name: openmrscore
  labels:
    app: openmrscore
    ver: 2.4.0
spec:
  containers:
    - name: openmrscore
      image: shaikkhajaibrahim/openmrs-core:2.4.0
      ports:
        - containerPort: 8080
          protocol: TCP