apiVersion: v1
kind: Pod
metadata: 
  name: mysql
  labels:
    app: db
    ver: 5.6
spec:
  containers:
    - name: mysql
      image: mysql:5.6
      ports:
        - containerPort: 3306
          protocol: TCP
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        - name: MYSQL_DATABASE
          value: openmrs
        - name: MYSQL_USER
          value: directdevops
        - name: MYSQL_PASSWORD
          value: directdevops
