apiVersion: v1
kind: ReplicationController
metadata:
  name: openmrs-rc
  labels:
    app: openmrs
    ver: 2.4.0
spec:
  replicas: 3
  selector:
    app: openmrscore
    ver: 2.4.0
  template:
    metadata:
      labels:
        app: openmrscore
        ver: 2.4.0
    spec:
      containers:
        - name: openmrscore
          image: shaikkhajaibrahim/openmrs-core:2.4.0
          ports:
            - containerPort: 8080
              protocol: TCP